-- V1__init_schema.sql
-- Schéma initial PostgreSQL, équivalent exact de celui produit jusqu'ici par
-- ddl-auto=update + schema-postgresql.sql (mécanisme remplacé par Flyway).
-- ddl-auto=validate vérifiera au démarrage que la table ci-dessous colle
-- toujours à l'entité JPA VehicleListing.

CREATE TABLE vehicle_listing (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version                 BIGINT       NOT NULL,          -- optimistic locking (@Version)
    source                  VARCHAR(255) NOT NULL,
    external_url            VARCHAR(1000) NOT NULL,          -- unique (idx_external_url)
    brand                   VARCHAR(255) NOT NULL,
    model                   VARCHAR(255) NOT NULL,
    vehicle_year            INTEGER      NOT NULL,           -- colonne "year" dans JPA
    mileage_km              INTEGER,
    price                   NUMERIC(10,2) NOT NULL,
    currency                VARCHAR(3)   NOT NULL,
    garage_city             VARCHAR(255),
    scraped_at              TIMESTAMP    NOT NULL,
    fuel_type               VARCHAR(20)  NOT NULL,           -- @Enumerated(EnumType.STRING)
    engine_displacement_cm3 INTEGER,
    first_registration_date DATE         NOT NULL,
    image_url               VARCHAR(2000)
);

CREATE INDEX idx_external_url ON vehicle_listing (external_url);
CREATE INDEX idx_brand_model   ON vehicle_listing (brand, model);
CREATE INDEX idx_fuel_type     ON vehicle_listing (fuel_type);

-- Insertion initiale facultative : aucune, données injectées par les scrapings.
